name: Build and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # 运行环境，选择最新的 Ubuntu

    steps:
    - name: Checkout repository  # 第一步：检出仓库内容
      uses: actions/checkout@v3
      
    - name: Install Python  # 第二步：安装 Python 环境
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # 选择适合的 Python 版本
        
    - name: Install PyInstaller  # 第三步：安装 PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
      
    - name: Build executable  # 第四步：使用 PyInstaller 打包
      run: |
        pyinstaller -F main/v2cnFont.py
        cp exeLib/texconv.exe dist/texconv.exe
        
    - name: Upload Artifact  # 第五步：上传生成的 dist 目录到 Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
